### ISSUE TITLE
Loads forever

### ISSUE THREAD

**Issue by saahildoshi** [Tiskua/PowerSchool-Helper#1]
The app loads forever on the loading screen. Everything is entered correctly.

**Comment by Tiskua** [comment]
Hello, thank you for reaching out. What information did you enter and did you make sure to change the URL in the settings menu?

**Comment by saahildoshi** [comment]
I entered my correct username and password, and the right url

**Comment by Tiskua** [comment]
What version of the app are you running and what is the url that you entered?

**Comment by saahildoshi** [comment]
Version 1.5.1 

https://ps.oconee.k12.ga.us/public/

**Comment by Tiskua** [comment]
Have you tried to delete the app and reinstall it? There might be an issue from updating to the new version

**Comment by saahildoshi** [comment]
I deleted the app and reinstalled it right now

**Comment by saahildoshi** [comment]
Still happening

**Comment by Tiskua** [comment]
Would you mind sending me a picture of the main screen of your PowerSchool website? Some schools have different layouts

**Comment by saahildoshi** [comment]
I really like the idea of this app and would love to have it

**Comment by saahildoshi** [comment]
Ok

**Comment by saahildoshi** [comment]
![Uploading 88399164-BE24-4B78-9573-2F5597A8E5B2.png…]()

**Comment by saahildoshi** [comment]
Did that send?

**Comment by Tiskua** [comment]
It is not loading

**Comment by Tiskua** [comment]
If it does not work you can email me: bransonsayshi@gmail.com

**Comment by BobJeff333** [comment]
Sorry, I have to go

**Comment by saahildoshi** [comment]
Ok

**Comment by saahildoshi** [comment]
Sent the photo by email

**Comment by Tiskua** [comment]
Can you send me one of the main page

**Comment by saahildoshi** [comment]
Yes

**Comment by saahildoshi** [comment]
Done

**Comment by Tiskua** [comment]
Ok I think I have found the issue. When you first download the app it tries to load quieter one. Since you have no information for it, it just keeps loading. I can fix this, but I will have to release a new update.

**Comment by saahildoshi** [comment]
ok, great

**Comment by saahildoshi** [comment]
I will not be able to test it today, but I will try it tomorrow, and get back with you

**Comment by Tiskua** [comment]
That's alright. It is gonna take a few days for me to fix it and apple to release it.

**Comment by saahildoshi** [comment]
Ok, when do you think it will be released

**Comment by saahildoshi** [comment]
A week or two?

**Comment by Tiskua** [comment]
I'm currently in the process of making an update, so probably by next week.

**Comment by saahildoshi** [comment]
Got it, I will close this issue.

**Comment by saahildoshi** [comment]
Do you have an update on when the update is coming out?
